Anti_Social_Freaks/Anti_Social_Freaks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('anti-social/' , include('Social_Network.urls')),


]

Anti_Social_Freaks/Social_Network/urls.py
from django .urls import path
from . import views
from django.contrib.auth.views import login,logout

app_name = 'Social_Network'



# all add your needed urls here
urlpatterns = [


    # Starting Page
    path('' , views.start  , name='start' ),

    # Sign Up, Log in and Log out
    # this is just a test make sure to try this path first to make sure that everyting is ok
    path('login/', login, {'template_name': 'Social_Network/login.html'},name= 'login' ),
    path('logout/', logout, {'template_name': 'Social_Network/logout.html'},name= 'logout'),
    path('register/', views.register, name='register'),
    path('home',views.home , name='home'), # home page
    path('profile', views.profile, name='profile'),  # profile page
    path('CommentPost/<int:post_id>/', views.addComment, name='addcomment'), # add a comment for a given post id
    path('LikePost/<int:post_id>/', views.addLike, name='addLike'), # add a Like for a given post id
    path('searchUser',views.search,name='search'), # Search for a user and go to it's profile
    path('AddFriend/<int:friend_id>/',views.addFriend,name='addfriend'),
    path('FollowFriend/<int:friend_id>/', views.followFriend, name='followfriend'),
    path('unFriend/<int:friend_id>/', views.unFriend, name='unfriend' ),
    path('FriendRequests/', views.showRequest, name='showrequest' ),
    path('FriendRequests/Confirm/<int:friend_id>/', views.confirmFriend, name='confirmfriend'),
    path('userProfile/<int:user_id>/', views.userProfile , name='userprofile'),
    path('connection/<int:user_id>/', views.checkConnection , name='connection')

]

Anti_Social_Freaks/status/urls.py
from django.conf.urls import url
from django.urls import path, include
from status.views import StatusView

urlpatterns = [
    path('', StatusView.as_view(), name='home'),
]

Anti_Social_Freaks/Social_Network/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime





class Post(models.Model):# shares is missing $$$$$$$$$$
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=2000)
    date = models.DateTimeField(blank=True,default=datetime.now)

    def __str__(self):
        return self.content


class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE ,null=True )

    def __str__(self):
        return self.content


class Like(models.Model):
    liker=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s %s' % (self.liker, 'Liked', self.post)


class Connection(models.Model):
    From = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_requests_created')
    To = models.ForeignKey(User, on_delete=models.CASCADE)
    interaction = models.IntegerField(blank=True)  # indicates how much a user interacts with another
    status = models.IntegerField()

    def __str__(self):
        if (self.status == 0):
            return '%s' % ("Pending")


        elif (self.status == 1):
            return '%s %s %s' % ("Friends" , self.From.username, self.To.username)


        elif (self.status == 2):
            return '%s' % ("Declined")

        elif (self.status == 3):
            return '%s' % ("Blocked")


        elif (self.status == 4):
            return '%s' % ("Followed")

        else:
            return '%s' % ("Blocked")

    '''
    status code
    pending : 0
    Friends : 1
    Declined : 2
    Blocked : 3
    Follow :4
    '''

Anti_Social_Freaks/Social_Network/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'password1',
                  'password2'
        )
        #then have to define a function that allows the form to save the data to the model.



    def save(self, commit=True):


        try:
            user = super(RegistrationForm,self).save(commit = False)

        except ValueError:
            raise forms.ValidationError("This Username is already taken or Password does not match")




        if commit:
            user.save()





class postForm(forms.Form):
    post = forms.CharField(max_length=2000)



class commentForm(forms.Form):
    comment = forms.CharField(max_length=1000)




class searchForm(forms.Form):
    username = forms.CharField(max_length=150)

Anti_Social_Freaks/Social_Network/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.shortcuts import redirect
from django.contrib.auth import logout
from collections import defaultdict

# Create your views here.


def start(request):
    return render(request,'Social_Network/start.html')




####################### Log In and Log Out

def NewsFeed(id):
    current_user = User.objects.get(id=id)
    my_connections = Connection.objects.filter(From=current_user, status=1)
    time_line_posts=[]
    for connection in my_connections:
        friend=User.objects.get(id=connection.To.id)
        friend_post=Post.objects.filter(publisher=friend).order_by('-date')
        time_line_posts.extend(friend_post)


    return time_line_posts



def is_friend(myid,friend_id):
    current_user=User.objects.get(id=myid)
    friend=User.objects.get(id=friend_id)

    my_connections = Connection.objects.filter(From=current_user, status=1)
    for connection in my_connections:
        if(connection.To.id==friend.id):
            return True

    return False


def getSuggestedFriends(id):
    current_user= User.objects.get(id=id)
    my_connections = Connection.objects.filter(From=current_user, status=1)  # bagib el friends bto3i
    suggested_friends = []
    suggested_connections = []

    suggested_friends_dict=defaultdict(int)

    for connection in my_connections:
        friend = User.objects.get(id=connection.To.id)
        suggested_connections.extend(Connection.objects.filter(From=friend, status=1))

    for suggested_connection in suggested_connections:
        suggested_friend = User.objects.get(id=suggested_connection.To.id)
        if suggested_friend.id != current_user.id:
            suggested_friends_dict[suggested_friend] = suggested_friends_dict[suggested_friend]+1
           # suggested_friends.append(suggested_friend)

    for suggested_friend in suggested_friends_dict:
        if((suggested_friends_dict[suggested_friend]>=2) and not (is_friend(id,suggested_friend.id))):
            suggested_friends.append(suggested_friend)

    return suggested_friends


def register(request):
    if request.method =='POST':

        form = RegistrationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('/anti-social/login')
    else:
        form= RegistrationForm()

        args={'form':form}
        return render(request,'Social_Network/registration.html',args)

def login_redirect( request ):
    return redirect("/anti-social/home")

def logout_view(request):
    logout(request)
    return render(request,'Social_Network/logout.html')
####################### Log In and Log Out

def home(request): # news feed and posts from other freaks
    if request.method == 'POST':
        # Create a form instance
        post_form = postForm(request.POST)
        if(post_form.is_valid()):
            user_of_post = User.objects.get(id=request.user.id)
            post_of_user = post_form.cleaned_data['post']
            post = Post(publisher=user_of_post , content=post_of_user)
            post.save()
    else:
        post_form = postForm()

    search_form = searchForm()
    comment_form = commentForm()
    posts = NewsFeed(request.user.id)
    suggested_friends = getSuggestedFriends(request.user.id)
    context = {
        'user': request.user,
        'post_form': post_form,
        'comment_form': comment_form,
        'posts': posts,
        'search_form' : search_form,
        'suggested_friends' : suggested_friends
    }

    return render(request, 'Social_Network/home.html', context)

def addComment(request,post_id):
    comment_form = commentForm(request.POST)

    if (comment_form.is_valid()):
        user_of_comment = User.objects.get(id=request.user.id)
        post_of_comment = Post.objects.get(id=post_id)
        comment_of_post = comment_form.cleaned_data['comment']
        comment = Comment(post=post_of_comment,content=comment_of_post,commenter=user_of_comment)
        comment.save()

    return redirect('Social_Network:home')

def addLike(request,post_id):
    user_of_like = User.objects.get(id=request.user.id)
    post_of_like = Post.objects.get(id=post_id)
    like = Like(post=post_of_like,liker=user_of_like)
    like.save()
    return redirect('Social_Network:home')

def search(request):
    search_form = searchForm(request.POST)
    user_of_search = User.objects.get(id=request.user.id)
    if (search_form.is_valid()):
        username = search_form.cleaned_data['username']
        user_of_search = User.objects.get(username=username)

    posts = Post.objects.filter(publisher=user_of_search)
    context = {'username' : user_of_search , 'posts' :posts}
    return render(request, 'Social_Network/profile.html',context)



def profile(request):
    user = User.objects.get(id = request.user.id)
    posts = Post.objects.filter(publisher=user).order_by('-date')
    friend_requests=Connection.objects.filter(To=request.user,status=0)
    context = {'profile' : user , 'posts':posts , 'friend_requests' : friend_requests}
    return render(request,'Social_Network/myprofile.html',context)


def addFriend(request,friend_id):
    user_from = User.objects.get(id=request.user.id)
    user_to   = User.objects.get(id=friend_id)

    test_connection = Connection.objects.filter(From= user_from , To= user_to)

    if(test_connection.exists()):
        test_connection = test_connection[0]
        test_connection.status = 0
        test_connection.save()

    else:
        connection = Connection(From=user_from,To=user_to,status=0,interaction=0)
        connection.save()

    return redirect('Social_Network:home')

def unFriend(request,friend_id):
    user_from = User.objects.get(id=request.user.id)
    user_to   = User.objects.get(id=friend_id)

    test_connection = Connection.objects.filter(From= user_from , To= user_to)

    if(test_connection.exists()):
        connection1 = test_connection[0]
        connection1.delete()

    test_connection2 = Connection.objects.filter(From=user_to, To=user_from)

    if (test_connection2.exists()):
        connection2 = test_connection2[0]
        connection2.delete()


    return redirect('Social_Network:home')

def followFriend(request,friend_id):
    user_from = User.objects.get(id=request.user.id)
    user_to   = User.objects.get(id=friend_id)

    test_connection = Connection.objects.filter(From= user_from , To= user_to)

    if(test_connection.exists()):
        test_connection = test_connection[0]
        test_connection.status = 4
        test_connection.save()

    else:
        connection = Connection(From=user_from,To=user_to,status=4,interaction=0)
        connection.save()

    return redirect('Social_Network:home')

def confirmFriend(request,friend_id):
    user_to = User.objects.get(id=request.user.id)
    user_from   = User.objects.get(id=friend_id)

    test_connection = Connection.objects.filter(From= user_from , To= user_to)

    if(test_connection.exists()):# must exist
        test_connection = test_connection[0]
        test_connection.status = 1
        test_connection.save()
    #cheking reverse connection
    test_connection = Connection.objects.filter(From=user_to, To=user_from)

    # el goz2  da 34an lw A---->(add)B && B------>(follw)A
    if (test_connection.exists()):#may not exist
        test_connection = test_connection[0]
        test_connection.status = 1
        test_connection.save()
    else:
        connection = Connection(From=user_to,To=user_from,status=1,interaction=0)# creating reverse connection
        connection.save()

    return redirect('Social_Network:home')

def showRequest(request):

    friend_requests=Connection.objects.filter(To=request.user,status=0)
    context={
        'friend_requests' : friend_requests
    }
    return render(request, 'Social_Network/Friend_requests.html', context)



def userProfile(request,user_id):

    user = User.objects.get(id = user_id)
    posts = Post.objects.filter(publisher=user)
    context = {'username': user , 'posts' : posts}
    return render(request, 'Social_Network/profile.html', context)


######################### Graph

def generate_graph(graph):
    graph_connections = Connection.objects.filter(status=1)

    for connection in graph_connections:
        graph.add_edge(connection.From.id, connection.To.id)




class Graph:
    # Constructor
    def __init__(self):
        # default dictionary to store graph
        self.graph = defaultdict(list)
        self.visited = defaultdict(bool)
        self.adj_matrix = defaultdict(list)

    #function to add edges
    def add_edge(self, u, v):
        self.graph[str(u)].append(str(v))
        user_from = User.objects.get(id=u)
        user_to = User.objects.get(id=v)
        self.adj_matrix[user_from.username].append(user_to.username)

    #v is the starting node and u is the node we are trying to find a connection between it and v
    def explore(self,v, u, connected):
        print(v)
        self.visited[str(v)] = True
        if str(v) == str(u):
            connected =True

        for i in self.graph[str(v)]:
            if self.visited[i] == False:
                connected = self.explore(i, u, connected)

        return connected



    def DFS(self, v, u):

        connected =False
        for i in self.graph:
            self.visited[i] = False



        return self.explore(v, u, connected)





def checkConnection(request,user_id):
    user_to = User.objects.get(id=user_id)
    user_from = User.objects.get(id = request.user.id)
    g = Graph()
    generate_graph(g)
    connection = g.DFS(user_from.id,user_to.id)
    print(g.adj_matrix)
    adj_matrix = g.adj_matrix

    graph_string = []


    for y in adj_matrix:
        s = y
        s = s + ' -> '
        for x in adj_matrix[y]:
            s = s + x
            s = s + ', '

        s = s[:-2]
        graph_string.append(s)

    context = { 'connection' : connection , 'adj_matrix' : graph_string}

Anti_Social_Freaks/Social_Network/templates/Social_Network/Friend_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>
{% for request in friend_requests %}

  <li> {{request.From.username}}

    <form method="post"  action="Confirm/{{ request.From.id  }}/ ">
    {% csrf_token %}
    <input type = "submit" value="Confirm" />

    </form>

</li>

{% endfor %}

</ul>

</body>
</html>

Anti_Social_Freaks/Social_Network/templates/Social_Network/connection.html
{% load staticfiles %}



<!DOCTYPE html>
  <html>
  <head>
    <title>Anty-Social Freaks</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- If IE use the latest rendering engine -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


  <style>
  * {
   margin: 0;
   padding: 0;
  }
  .backGround{
      background-image: url({% static 'Social_Network/images/x2.jpg' %});
      background-size: cover;
    }
  .icon{
    height :30px;
    width: 30px;
    margin-top: 10px;
    margin-bottom: 10px;

  }
  .center {
    margin: auto;
    width: 20%;
    height: 10%;
    border: 3px solid green;
    padding: 10px;
}
  .FontEdits {
      font-family: Times, serif ;
  }
  .MainTitle{
    font-size: 50px;
    text-align: center;
    font-weight: bold;
    color: rgba(255, 255, 255, 1);

  }
  .SecondTitle{
    margin-top: 1%;
    font-size: 30px;
    text-align: center;
    color: rgba(255, 255, 255, 1);


  }
.MainContainer{
      background-color: rgba(34, 34, 34, 0.7) ;
      width: 90%;
      margin: auto;
      margin-top: 10%;
      padding-top: 20px;
      padding-bottom: 30px;
      position: relative;
      color: lime;
       font-size: 32px;
    }

  .page-header
 {
      margin-top: 1%;
    font-size: 200px;
    text-align: center;
    color: rgba(255, 255, 255, 1);


 }

  .two
  {
      margin-top: 0;
      text-align: center;
  }


  </style>
  </head>
  <body class="backGround">



  <nav class="navbar navbar-inverse ">
      <div class="container-fluid">
        <div class="navbar-header">
          <img class="icon" src=" {% static 'Social_Network/images/White_Globe_Icon.png' %} " />

          <a  class="navbar-brand" href="{% url 'Social_Network:home' %}">Anti-Social Freaks</a>
        </div>

      </div>
    </nav>





    <div class="MainContainer">
    <h3 style="color: #bce8f1; text-align: center">Your Connection is {{ connection }}</h3>

    </div>



  <div class = "page-header">

      <h5 style="font-size: 70px"> The Adjacency list of the users Graph</h5>


</div>


  <div class="MainContainer two">

{% for x in adj_matrix %}

    {{ x }}

    <br>

  {% endfor %}

  </div>

  </body>
  </html>

Anti_Social_Freaks/Social_Network/templates/Social_Network/profile.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Timeline</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .clearfix::after, .clearfix::before {
      content: "";
      clear: both;
      display: block;
    }
  .icon{
    height :30px;
    width: 30px;
    margin-top: 10px;
    margin-bottom: 10px;
    }

  .backGround{
      background-image: url({% static 'Social_Network/images/x2.jpg' %});
      background-size: cover;
    }

  /**/
  /* Profile container */
  .profile {
    margin: 20px 0;
  }

  /* Profile sidebar */
  .profile-sidebar {
    padding: 20px 0 10px 0;
    background: rgba(34,34,34,0.7);
  }

  .profile-userpic img {
    float: none;
    margin: 0 auto;
    width: 50%;
    height: 50%;
    -webkit-border-radius: 50% !important;
    -moz-border-radius: 50% !important;
    border-radius: 50% !important;
  }

  .profile-usertitle {
    text-align: center;
    margin-top: 20px;
  }

  .profile-usertitle-name {
    color: white;
    font-size: 16px;
    font-weight: 600;
    margin-bottom: 7px;
  }

  .profile-usertitle-job {
    text-transform: uppercase;
    color: #5b9bd1;
    font-size: 12px;
    font-weight: 600;
    margin-bottom: 15px;
  }

  .profile-userbuttons {
    text-align: center;
    margin-top: 10px;
  }

  .profile-userbuttons .btn {
    text-transform: uppercase;
    font-size: 11px;
    font-weight: 600;
    padding: 6px 15px;
    margin-right: 5px;
  }

  .profile-userbuttons .btn:last-child {
    margin-right: 0px;
  }

  .profile-usermenu {
    margin-top: 30px;
  }

  .profile-usermenu ul li {
    border-bottom: 1px solid #f0f4f7;
  }

  .profile-usermenu ul li:last-child {
    border-bottom: none;
  }

  .profile-usermenu ul li a {
    color: #93a3b5;
    font-size: 14px;
    font-weight: 400;
  }

  .profile-usermenu ul li a i {
    margin-right: 8px;
    font-size: 14px;
  }

  .profile-usermenu ul li a:hover {
    background-color: #fafcfd;
    color: #5b9bd1;
  }

  .profile-usermenu ul li.active {
    border-bottom: none;
  }

  .profile-usermenu ul li.active a {
    color: #5b9bd1;
    background-color: #f6f9fb;
    border-left: 2px solid #5b9bd1;
    margin-left: -2px;
  }

  /* Profile Content */
  .profile-content {
    padding: 20px;
    background: #fff;
    min-height: 460px;
  }
  .GeneratedContainers{
    background-color: rgba(34, 34, 34, 0.7) ;
    margin-top: 25px;
    padding-top: 15px;
    padding-bottom: 15px;
    padding-right: 15px;
    padding-left: 15px;

  }
  .SuggestedFriendsContainer{
    background-color: rgba(34, 34, 34, 0.7) ;
    margin-top: 5px;
    margin-bottom: 5px;
    padding-top: 5px;
    padding-bottom: 5px;
    padding-right: 5px;
    padding-left: 5px;
  }
   #PostLabel{
    background-color: #f5f5f5;
    margin-top: 5px;
    margin-bottom: 5px;
    padding-top: 5px;
    padding-bottom: 35px;
    padding-right: 5px;
    padding-left: 5px;
  }
  #CommentLabel{
    background-color: #f5f5f5;
    margin-top: 5px;
    margin-bottom: 5px;
    margin-left: 10px;
    padding-top: 5px;
    padding-bottom: 25px;
    padding-right: 5px;
    padding-left: 5px;
    width: 84%;
    display: inline-block;
  }

  #PostTextArea {
  resize: vertical;
  height: 100px;
  width: 100%

  }

  #CommentTextArea{
    margin-top: 10px;
    margin-bottom: 10px;
    margin-right: 10px;
    margin-left: 10px;
    resize: vertical;
    height: 50px;
    width: 90%;
    display: inline-block;
  }
  #CommentPP{
    display: inline-block;
    border-radius: 50%;
    width: 5%;
    height: 5%;
  }
  #CommentOwnerInfo{
    display: block;
  }

  </style>
</head>
<body class="backGround">
<nav class="navbar navbar-inverse ">
      <div class="container-fluid">
        <div class="navbar-header">
          <img class="icon" src="{% static 'Social_Network/images/White_Globe_Icon.png' %}" />
          <a  class="navbar-brand" href="">Anti-Social Freaks</a>
        </div>
            <ul class="nav navbar-nav navbar-right">



              <li> <a href="{%   url 'Social_Network:home' %}">Timeline</a></li>
              <li><a href="{%   url 'Social_Network:profile' %}">My Profile</a></li>
              <li><a href="{% url 'Social_Network:logout' %}">Sign Out</a></li>



            </ul>
      </div>
    </nav>


<div class="container-fluid">
    <div> <!-- class="row profile"> -->
    <div class="col-md-2">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <img src="{% static 'Social_Network/images/Profile-Pic.jpg' %}" class="img-responsive" alt="">
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            {{ user.username }}
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">

            <form action="logout/" method="post">

                {% csrf_token%}

          <button type="submit" class="btn btn-danger btn-sm">Sign Out</button>

                </form>
        </div>
        <!-- END SIDEBAR BUTTONS -->

      </div>
    </div>
    <div class="col-sm-8" style="color: #5bc0de">


{% for post in posts %}

            <div class="GeneratedContainers">
            <div>
                <img src="{% static 'Social_Network/images/Profile-Pic.jpg' %}" class="rounded-circle" id="CommentPP">
                <a href= "#"style="color: white;" > {{ post.publisher.username }}</a>
            </div>
            <div>
              <p id="PostLabel">{{ post.content }}</p>
                <p>at: {{ post.date }}</p>
                <p>
                        Likes = {{    post.like_set.count }}
                </p>
            </div>


            <div>

                <form method="post"  action="LikePost/{{ post.id }}/ ">
    {% csrf_token %}
                     <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-up"></i> Like</button>

                </form>



            </div>

            <h5>Comments</h5>

{% for comment in post.comment_set.all %}
              <div> <!-- Comment part -->
                <img src="{% static 'Social_Network/images/Profile-Pic.jpg' %}" class="rounded-circle" id="CommentPP">
                <a href= "#" style="color: white; " > {{ comment.commenter.username }}</a>
                <div class="clearfix">
                  <p id="CommentLabel"> {{comment.content }} </p>

                </div>

              </div>



              {% endfor %}


<form method="post"  action="CommentPost/{{ post.id }}/ ">
    {% csrf_token %}
    {{ comment_form }}

              <button type="submit" class="btn btn-info"><i class="glyphicon glyphicon-comment"></i> Comment </button>

</form>


            </div>








  {% endfor %}

    </div>




    <div class="col-sm-2 sidenav">
      <div class="SuggestedFriendsContainer">
        <p style="color: white;">Options you have to this Freak called {{ username.username }} </p>
      </div>






      <div class="SuggestedFriendsContainer">




<form method="post"  action="{%   url 'Social_Network:followfriend' username.id  %}">

    {% csrf_token %}
      <button type="submit" class="btn btn-warning btn-sm">Follow</button>

</form>

          <br>

<form method="post"  action="{%   url 'Social_Network:addfriend' username.id  %}">
    {% csrf_token %}
 <button type="submit" class="btn btn-success btn-sm">Add as a Freak</button>
</form>


<br>

  <form method="post"  action="{%   url 'Social_Network:unfriend' username.id  %}">

    {% csrf_token %}

     <button type="submit" class="btn btn-danger btn-sm">UnFriend</button>

</form>


<br>

            <form method="post"  action="{%   url 'Social_Network:connection' username.id  %}">

    {% csrf_token %}

     <button type="submit" class="btn btn-dark btn-sm">Check Connection</button>

            </form>






      </div>



    </div>
  </div>
</div>






</body>
</html>

Anti_Social_Freaks/Social_Network/templates/Social_Network/start.html
{% load staticfiles %}



<!DOCTYPE html>
  <html>
  <head>
    <title>Anty-Social Freaks</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- If IE use the latest rendering engine -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


  <style>
  * {
   margin: 0;
   padding: 0;
  }
  .backGround{
      background-image: url({% static 'Social_Network/images/x2.jpg' %});
      background-size: cover;
    }
  .icon{
    height :30px;
    width: 30px;
    margin-top: 10px;
    margin-bottom: 10px;

  }
  .center {
    margin: auto;
    width: 20%;
    height: 10%;
    border: 3px solid green;
    padding: 10px;
}
  .FontEdits {
      font-family: Times, serif ;
  }
  .MainTitle{
    font-size: 50px;
    text-align: center;
    font-weight: bold;
    color: rgba(255, 255, 255, 1);

  }
  .SecondTitle{
    margin-top: 1%;
    font-size: 30px;
    text-align: center;
    color: rgba(255, 255, 255, 1);


  }
.MainContainer{
      background-color: rgba(34, 34, 34, 0.7) ;
      width: 40%;
      margin: auto;
      margin-top: 10%;
      padding-top: 20px;
      padding-bottom: 30px;
      position: relative;
    }



  </style>
  </head>
  <body class="backGround">



  <nav class="navbar navbar-inverse ">
      <div class="container-fluid">
        <div class="navbar-header">
          <img class="icon" src=" {% static 'Social_Network/images/White_Globe_Icon.png' %} " />

          <a  class="navbar-brand" href="">Anti-Social Freaks</a>
        </div>

      </div>
    </nav>



    <div class="MainContainer">
    <h1 class="MainTitle">Hello There!!</h1>

    <h2 class="SecondTitle"> New to the website?  <a href="{%   url 'Social_Network:register' %}" style="font-weight: bold; font-size: 40px; color: #2b669a;
     text-decoration: none ; ">Sign Up</a></h2>

     <h2 class="SecondTitle">Already a member? <a href="login/" style="font-weight: bold; font-size: 40px; color: #d9534f;
     text-decoration: none ; ">Log In</a></h2>


    <br><br>
    #we own your data

    </div>

  </body>
  </html>